image: ubuntu:bionic

before_script:
  - apt-get update -qq && apt-get install -y -qq python3 python3-pip ninja-build gcc gcc-multilib flex bison valgrind time git zip
  - pip3 install --user meson
  - export PATH=$HOME/.local/bin:$PATH

stages:
  - Build
  - Test
  - Package

Build:
  stage: Build
  artifacts:
    paths:
      - builddir/
  script:
    - meson builddir --buildtype=debug
    - ninja -C builddir

UnitTests:
  stage: Test
  dependencies:
    - Build
  script:
    - meson test -v -C builddir

UnitTestsLeaks:
  stage: Test
  dependencies:
    - Build
  script:
    - meson test --wrapper 'valgrind --error-exitcode=1 --leak-check=full --track-origins=yes' -v -C builddir

IntegrationTests:
  stage: Test
  dependencies:
    - Build
  script:
    - cd builddir
    - ../scripts/run_integration_tests

Package:
  stage: Package
  artifacts:
    paths:
      - team_XX_final.zip
  script:
    - git archive --prefix=team_XX_final/ --format=zip HEAD > team_XX_final.zip
